package sys.bg.model.base;

// Generated 2014-4-15 23:00:45 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SysDatadicType generated by hbm2java
 */
@Entity
@Table(name = "sys_datadic_type", catalog = "es", uniqueConstraints = @UniqueConstraint(columnNames = "type_code"))
public class SysDatadicType implements java.io.Serializable {

	private String id;
	private String typeCode;
	private String typeName;
	private String description;
	private String seq;
	private Date createTime;
	private String creatorId;
	private Date updateTime;
	private String updaterId;

	public SysDatadicType() {
	}

	public SysDatadicType(String id, Date createTime, Date updateTime) {
		this.id = id;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public SysDatadicType(String id, String typeCode, String typeName,
			String description, String seq, Date createTime, String creatorId,
			Date updateTime, String updaterId) {
		this.id = id;
		this.typeCode = typeCode;
		this.typeName = typeName;
		this.description = description;
		this.seq = seq;
		this.createTime = createTime;
		this.creatorId = creatorId;
		this.updateTime = updateTime;
		this.updaterId = updaterId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 30)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "type_code", unique = true, length = 30)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_name", length = 30)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "seq", length = 30)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "creator_id", length = 30)
	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updater_id", length = 30)
	public String getUpdaterId() {
		return this.updaterId;
	}

	public void setUpdaterId(String updaterId) {
		this.updaterId = updaterId;
	}

}
